name: pain au chocolat

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
  SOURCE: iMariee/chocolat
  MIRROR: "EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-marie.incandela"
  EXECUTABLE: "a.out"
  CODING_STYLE: "coding-style.sh"
  GITHUB_SSH_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

jobs:
  check_coding_style:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: coding style
      run: ./$CODING_STYLE $(pwd) $(pwd)


  repository_mirroring:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Push content to the mirror repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: git@github.com:${{ env.MIRROR }}.git
        ssh_private_key: ${{ env.GITHUB_SSH_KEY }}
