name: pain au chocolat

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
  SOURCE: iMariee/chocolat
  MIRROR: "EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-marie.incandela"
  EXECUTABLE: "test"
  CODING_STYLE: "coding-style.sh"
  VERIFY_STYLE: "verify_style.sh"
  VERIFY_EXEC: "verify_exec.sh"
  GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: coding style
      run: ./$CODING_STYLE $(pwd) $(pwd)
    - name: give autorization
      run: chmod 777 ./$VERIFY_STYLE
    - name: display coding style
      run: ./$VERIFY_STYLE

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: compile
      run: make
    - name: clean files
      run: make clean
    - name: give autorization
      run: chmod 777 ./$VERIFY_EXEC
    - name: verify exec
      run: ./$VERIFY_EXEC $EXECUTABLE

  repository_mirroring:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Push content to the mirror repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: git@github.com:${{ env.MIRROR }}.git
        ssh_private_key: ${{ env.GIT_SSH_PRIVATE_KEY }}
